[package]
name = "atlaspack_plugin_transformer_tokens"
version = "0.1.0"
authors = ["Marcin Szczepanski <mszczepanski@atlassian.com>"]
edition = { workspace = true }
description = "Atlaskit Tokens transformer plugin for the Atlaspack Bundler"

[lints]
workspace = true

[dependencies]
atlaspack_atlaskit_tokens = { path = "../atlaspack_atlaskit_tokens" }
atlaspack_core = { path = "../atlaspack_core" }
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
atlaspack_sourcemap = { path = "../atlaspack_sourcemap" }
anyhow = { workspace = true }
async-trait = { workspace = true }
parcel_sourcemap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }


[dev-dependencies]
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["full"] }
