[package]
name = "atlaspack_memory_profiler"
version = "0.1.0"
edition = { workspace = true }
authors = ["Atlassian"]

[lints]
workspace = true

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
memory-stats = "1.0"
serde = { workspace = true }
