[package]
name = "atlaspack_plugin_transformer_json"
version = "0.1.0"
authors = ["Monica Olejniczak <monica.j.olejniczak@gmail.com>"]
edition = { workspace = true }
description = "Json transformer plugin for the Atlaspack Bundler"

[lints]
workspace = true

[dependencies]
atlaspack_core = { path = "../atlaspack_core" }

anyhow = { workspace = true }
async-trait = { workspace = true }
json = { workspace = true }
json5 = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
tokio = { workspace = true, features = ["full"] }
