[package]
name = "atlaspack_vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
git2 = { workspace = true, default-features = false }
hex = { workspace = true }
nom = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
