[package]
authors = ["Monica Olejniczak <monica.j.olejniczak@gmail.com>"]
name = "atlaspack_sourcemap"
version = "0.1.0"
edition = { workspace = true }
description = "Sourcemaps for Atlaspack"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
regex = { workspace = true }
rkyv = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
vlq = { workspace = true }
base64-simd = { workspace = true }
data-url = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
