[package]
name = "atlassian_swc_compiled_css_strip_runtime"
version = "0.0.1"
edition = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
atlassian_swc_compiled_css = { workspace = true }
atlaspack_core = { path = "../atlaspack_core" }
oxc_resolver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
swc_core = { workspace = true, features = [
  "ecma_plugin_transform",
  "ecma_visit",
  "ecma_ast",
  "ecma_utils",
  "ecma_codegen",
  "ecma_parser",
  "common"
] }
urlencoding = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
