[package]
name = "compiled_strip_runtime"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
compiled_babel = { package = "atlassian_swc_compiled_css", path = "../atlassian-swc-compiled-css" }
oxc_resolver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
swc_core = { workspace = true, features = [
  "ecma_plugin_transform",
  "ecma_visit",
  "ecma_ast",
  "ecma_utils",
  "common"
] }
urlencoding = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
