[package]
name = "swc_atlaskit_tokens"
description = "SWC visitor for @atlaskit/tokens (Atlassian Design System tokens)"
version = "0.0.7"
edition = { workspace = true }
license = "Apache-2.0"
repository = "https://bitbucket.org/atlassian/atlassian-frontend-mirror"
readme = "README.md"

include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
anyhow = { workspace = true }
swc_core = { workspace = true, features = ["common", "ecma_visit", "ecma_ast"] }
once_cell = { workspace = true }
serde_json = { workspace = true }
serde_json5 = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
swc_core = { workspace = true, features = [
  "ecma_parser",
  "ecma_plugin_transform",
] }
testing = { workspace = true }
tempfile = { workspace = true }
